name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

# 生产环境配置 (对应你的 main 分支)
[env.main]
kv_namespaces = [
  { binding = "KV", id = "bbd64c2ad2dc4f49ab6e22430c9f911b" }
]
